name: Automated Version Bump
description: Automated version bump for npm packages.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: chevron-up
  color: blue
inputs:
  tag-prefix:
    description: 'Prefix that is used for the git tag'
    default: ''
    required: false
  minor-wording:
    description: 'Words list that trigger a minor version bump'
    default: 'feat,minor'
    required: false
  major-wording:
    description: 'Words list that trigger a major version bump'
    default: 'BREAKING CHANGE,major'
  patch-wording:
    description: 'Words list that trigger a patch version bump'
  rc-wording:
    description: 'Words list that trigger a patch version bump'
    default: 'pre-alpha,pre-beta,pre-rc'
  skip-tag:
    description: 'Avoid to add a TAG to the version update commit'
    default: 'false'
    required: false
  PACKAGEJSON_DIR:
    description: 'Custom dir to the package'
    default: ''
    required: false
